services:
  backend:
    container_name: hello-headless-blender-backend
    image: hello-headless-blender-backend
    platform: linux/amd64
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/scenes:/app/scenes
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    depends_on:
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
  redis:
    container_name: hello-headless-blender-redis
    image: redis:7.4.1-alpine
    # ports:
    #   - 6379:6379
    volumes:
      - "./redis/data:/data"
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 2s
      timeout: 5s
      retries: 15
  minio:
    container_name: hello-headless-blender-minio
    image: minio/minio:RELEASE.2025-05-24T17-08-30Z
    volumes:
      - "./minio/data:/data"
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: minio server --console-address ":9001" /data
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 5s
      retries: 5
